ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DATA_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DATA_ACCESSED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DATA_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DATA_DELETED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'MATCH_SCORE_FEEDBACK_PROVIDED';
